services:
  ts2uml-web:
    image: joanvilarrasa/ts2uml-web:latest
    container_name: ts2uml-web
    restart: unless-stopped 
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - VITE_PASTEBIN_URL=https://ts2uml.com/pastebin
      - VITE_WEB_URL=https://ts2uml.com
    ports:
      - "3100:80"
    networks:
      - vps-network

  ts2uml-pastebin:
    image: danielszabo99/microbin:latest
    container_name: ts2uml-pastebin
    restart: always
    ports:
     - "3101:8080"
    volumes:
     - ./microbin-data:/app/microbin_data
    environment:
      MICROBIN_PUBLIC_PATH: https://ts2uml.com/pastebin
    networks:     
      - vps-network

networks:
  vps-network:
    external: true