services:
  ts2uml-web:
    image: joanvilarrasa/ts2uml-web:latest
    container_name: ts2uml-web
    restart: unless-stopped 
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3100:80"

  ts2uml-microbin:
    image: danielszabo99/microbin:latest
    restart: always
    ports:
     - "3101:8080"
    volumes:
     - ./microbin-data:/app/microbin_data
    networks:
      - vps-network

networks:
  vps-network:
    external: true  # Important: This tells Docker it's an existing network