services:
  ts2uml-web:
    image: joanvilarrasa/ts2uml-web:latest
    container_name: ts2uml-web
    restart: unless-stopped 
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    networks:
      - vps-network

  ts2uml-pastebin:
    image: danielszabo99/microbin:latest
    container_name: ts2uml-pastebin
    restart: always
    ports:
     - "8080:8080"
    volumes:
     - ./microbin-data:/app/microbin_data
    networks:
      - vps-network

networks:
  vps-network:
    external: true  # Important: This tells Docker it's an existing network