services:
  ts2uml-web:
    image: joanvilarrasa/ts2uml-web:latest
    container_name: ts2uml-web
    restart: unless-stopped 
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3100:80"
    environment:
      - VITE_PASTEBIN_URL=http://localhost:3101
      - VITE_WEB_URL=http://localhost:5173

  ts2uml-pastebin:
    image: danielszabo99/microbin:latest
    container_name: ts2uml-pastebin
    restart: always
    ports:
     - "3101:8080"
    volumes:
     - ./microbin-data:/app/microbin_data