name: Deploy ts2uml to VPS (PRO)

on:
  push:
    branches:
      - main # Or your main branch for ts2uml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker buildx create --use
        docker buildx build -t joanvilarrasa/ts2uml-web:latest --push . -f ./Dockerfile.web

    - name: Copy docker-compose file to VPS
      run: |
        echo "${{ secrets.VPS_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        # Create the directory if it doesn't exist, then copy the docker-compose.yml file
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} 'mkdir -p ~/ts2uml'
        scp -o StrictHostKeyChecking=no -i private_key.pem ./docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:~/ts2uml/docker-compose.yml

    - name: Deploy to VPS
      env:
        # EXAMPLE:
        # TS2UML_API_KEY: ${{ secrets.TS2UML_API_KEY }}
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${{ secrets.VPS_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
          # Export any environment variables your ts2uml app needs
          # EXAMPLE:
          # export TS2UML_API_KEY=${{ secrets.TS2UML_API_KEY }}
          cd ~/ts2uml
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker compose down
          docker image rm joanvilarrasa/ts2uml-web:latest || true
          docker compose pull
          docker compose up -d
          cd ../reverse-proxy
          docker compose down
          docker compose up -d
        EOF
